# Generated by Django 5.0.6 on 2024-08-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_preinscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='cupos_restantes',
            field=models.IntegerField(default=0, verbose_name='Cupos Restantes'),
        ),
    ]
