# Generated by Django 5.0.6 on 2024-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_cupos_restantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='profesor',
            field=models.CharField(default='Por asignar', max_length=50),
        ),
    ]
