# Generated by Django 5.0.6 on 2024-08-19 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_cursos_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='contenido',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Contenido'),
        ),
    ]
