# Generated by Django 5.0.6 on 2024-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='es_predefinida',
            field=models.BooleanField(default=False),
        ),
    ]
